{% set name = "verticapy" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/verticapy-{{ version }}.tar.gz
  sha256: 369ec6b131445f650d4f5f78abe7c16a569267bee729d6c2204f51c3b8ca1fbc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
    - python {{ python_min }}
  run:
    - matplotlib-base >=3.5.2
    - numpy >=1.11.0
    - python >={{ python_min }}
    - python >={{ python_min }},<3.13a0
    - scipy >=1.0.0
    - vertica-python >=1.2.0
    - python-dateutil
    - python-graphviz >=0.9.0
    - requests-kerberos
    - tqdm >=4.0.0
    - pandas >=0.23.0
    - vertica_highcharts >=0.1.4
    - plotly >=5.10.0
    - pyyaml >=6.0.1

test:
  imports:
    - verticapy
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - pytest-timeout
    - pytest-cov
    - parameterized
    - mock
    - graphviz
    - geopandas
    - ipython
    - scikit-learn
    - xgboost <2.1.0
    - statsmodels
    - python {{ python_min }}

about:
  home: https://github.com/vertica/VerticaPy
  summary: VerticaPy simplifies data exploration, data cleaning and machine learning in Vertica.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vertica-cla
    - FernandezMathieu
    - oualib
    - afard
    - condacircus
